// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: pkg/rpc/admin/service.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Auth) Reset() {
	*x = Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_admin_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_service_proto_rawDescGZIP(), []int{0}
}

type Auth_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=Config,proto3" json:"Config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Auth_Request) Reset() {
	*x = Auth_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_admin_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_Request) ProtoMessage() {}

func (x *Auth_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_Request.ProtoReflect.Descriptor instead.
func (*Auth_Request) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Auth_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Auth_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error        string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
}

func (x *Auth_Response) Reset() {
	*x = Auth_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_admin_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_Response) ProtoMessage() {}

func (x *Auth_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_Response.ProtoReflect.Descriptor instead.
func (*Auth_Response) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Auth_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Auth_Response) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

var File_pkg_rpc_admin_service_proto protoreflect.FileDescriptor

var file_pkg_rpc_admin_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01,
	0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x1a, 0x77, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x44, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x35, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x0d, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d,
	0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_rpc_admin_service_proto_rawDescOnce sync.Once
	file_pkg_rpc_admin_service_proto_rawDescData = file_pkg_rpc_admin_service_proto_rawDesc
)

func file_pkg_rpc_admin_service_proto_rawDescGZIP() []byte {
	file_pkg_rpc_admin_service_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_rpc_admin_service_proto_rawDescData)
	})
	return file_pkg_rpc_admin_service_proto_rawDescData
}

var file_pkg_rpc_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_rpc_admin_service_proto_goTypes = []interface{}{
	(*Auth)(nil),          // 0: Auth
	(*Auth_Request)(nil),  // 1: Auth.Request
	(*Auth_Response)(nil), // 2: Auth.Response
	nil,                   // 3: Auth.Request.ConfigEntry
}
var file_pkg_rpc_admin_service_proto_depIdxs = []int32{
	3, // 0: Auth.Request.Config:type_name -> Auth.Request.ConfigEntry
	1, // 1: AdminService.Auth:input_type -> Auth.Request
	2, // 2: AdminService.Auth:output_type -> Auth.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_rpc_admin_service_proto_init() }
func file_pkg_rpc_admin_service_proto_init() {
	if File_pkg_rpc_admin_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_rpc_admin_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_rpc_admin_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_rpc_admin_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_rpc_admin_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_admin_service_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_admin_service_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_admin_service_proto_msgTypes,
	}.Build()
	File_pkg_rpc_admin_service_proto = out.File
	file_pkg_rpc_admin_service_proto_rawDesc = nil
	file_pkg_rpc_admin_service_proto_goTypes = nil
	file_pkg_rpc_admin_service_proto_depIdxs = nil
}
