name: CI
on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: enowars/action-cleanup-runner@v1
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          working-directory: service
          skip-pkg-cache: true
          skip-build-cache: true
  test:
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: enowars/action-cleanup-runner@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build service
        run: |
          cd service
          go build ./cmd/gosship
          go test -v ./...
      - name: Build checker
        run: |
          cd checker
          go build ./cmd/checker
          go test -v ./...
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install enochecker_test
        run: |
          python -m pip install --upgrade pip
          pip install enochecker-test
      - name: Start service
        run: |
          cd service
          docker-compose up -d
      - name: Start checker
        run: |
          cd checker
          docker-compose up -d
      - name: Run enochecker_test
        run: |
          enochecker_test
        env:
          ENOCHECKER_TEST_SERVICE_ADDRESS: host.docker.internal
          ENOCHECKER_TEST_CHECKER_ADDRESS: 127.0.0.1
          ENOCHECKER_TEST_CHECKER_PORT: 8080
  release:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: enowars/action-cleanup-runner@v1
      - uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
